# Generated by Django 4.1.3 on 2022-11-17 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
