# Generated by Django 4.1.3 on 2022-11-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('logo', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=500, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
