# Generated by Django 4.1.2 on 2022-11-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_review_delete_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=100)),
                ('review', models.TextField()),
                ('date', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=500)),
                ('star', models.IntegerField(default=1)),
            ],
        ),
    ]
