# Generated by Django 4.1.3 on 2022-11-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
